version: "3"
services:
  jenkins:
    build: jenkins/.
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - ./jenkins/jenkins_home:/var/jenkins_home
    - ./testapp/.m2:/root/.m2
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
  testapp:
    build: testapp/.
    volumes:
    - ./testapp/.m2:/root/.m2
